export const fantokenList = {
  testACM: '0x370BAe51E225D820cb7946e0Dd5b225FE5A65803',
  testAFC: '0xbd64B25CB19254a9500105C85bFb460fd8d37655',
  testATM: '0xd7a52e679342209f307184fC486b97B87501DCbd',
  testBAR: '0x63667746A7A005E45B1fffb13a78d0331065Ff7f',
  testCITY: '0xF2c97Cb2A5c4B308cc264d9e7c57BB67F4Dca874',
  testGAL: '0xfD3abAF3F340F93dCe1E491cA11B2FDc7E29dbDC',
  testInter: '0x4B5ADC364Ad140cd616585D4691D4D0C6Dcf6b21',
  testJUV: '0x1ED7858225dF2a3365d07dD7C08d165D6A399bE6',
  testMENGO: '0x840ff03C4D5881c6340B3B89FD1C83c7476eFc27',
  testPSG: '0xa4bf4104ec0109591077Ee5F4a2bFD13dEE1Bdf8',
  testSSU: '0x82248Bfd4ee23dE94831AE43d066756fF0C66faa',
  testTRA: '0xCfc70a8703c39581366ED97242475B61c34383df',
}

export const erc20Abi = [
  {
    constant: true,
    inputs: [],
    name: 'name',
    outputs: [
      {
        name: '',
        type: 'string',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      {
        name: '_spender',
        type: 'address',
      },
      {
        name: '_value',
        type: 'uint256',
      },
    ],
    name: 'approve',
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'totalSupply',
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      {
        name: '_from',
        type: 'address',
      },
      {
        name: '_to',
        type: 'address',
      },
      {
        name: '_value',
        type: 'uint256',
      },
    ],
    name: 'transferFrom',
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'decimals',
    outputs: [
      {
        name: '',
        type: 'uint8',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [
      {
        name: '_owner',
        type: 'address',
      },
    ],
    name: 'balanceOf',
    outputs: [
      {
        name: 'balance',
        type: 'uint256',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'symbol',
    outputs: [
      {
        name: '',
        type: 'string',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      {
        name: '_to',
        type: 'address',
      },
      {
        name: '_value',
        type: 'uint256',
      },
    ],
    name: 'transfer',
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [
      {
        name: '_owner',
        type: 'address',
      },
      {
        name: '_spender',
        type: 'address',
      },
    ],
    name: 'allowance',
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    payable: true,
    stateMutability: 'payable',
    type: 'fallback',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: 'owner',
        type: 'address',
      },
      {
        indexed: true,
        name: 'spender',
        type: 'address',
      },
      {
        indexed: false,
        name: 'value',
        type: 'uint256',
      },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: 'from',
        type: 'address',
      },
      {
        indexed: true,
        name: 'to',
        type: 'address',
      },
      {
        indexed: false,
        name: 'value',
        type: 'uint256',
      },
    ],
    name: 'Transfer',
    type: 'event',
  },
] as const

export const fanTokenAbi = [
  { type: 'constructor', inputs: [] },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'addMinter',
    inputs: [{ type: 'address', name: 'account' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'addPauser',
    inputs: [{ type: 'address', name: 'account' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '' }],
    name: 'allowance',
    inputs: [
      { type: 'address', name: 'owner' },
      { type: 'address', name: 'spender' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '' }],
    name: 'approve',
    inputs: [
      { type: 'address', name: 'spender' },
      { type: 'uint256', name: 'value' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '' }],
    name: 'balanceOf',
    inputs: [{ type: 'address', name: 'account' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'batchTransfer',
    inputs: [
      { type: 'address', name: '_from' },
      { type: 'address[]', name: '_to' },
      { type: 'uint256[]', name: '_values' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'burn',
    inputs: [
      { type: 'address', name: 'account' },
      { type: 'uint256', name: 'value' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint8', name: '' }],
    name: 'decimals',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '' }],
    name: 'decreaseAllowance',
    inputs: [
      { type: 'address', name: 'spender' },
      { type: 'uint256', name: 'subtractedValue' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '' }],
    name: 'getCirculatingSupply',
    inputs: [
      { type: 'uint256', name: 'offset' },
      { type: 'uint256', name: 'count' },
      { type: 'uint256', name: 'cap' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: 'tokenOwner' }],
    name: 'getOwner',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '' }],
    name: 'getOwnersCount',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '' }],
    name: 'increaseAllowance',
    inputs: [
      { type: 'address', name: 'spender' },
      { type: 'uint256', name: 'addedValue' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'initialize',
    inputs: [
      { type: 'string', name: 'name' },
      { type: 'string', name: 'symbol' },
      { type: 'uint8', name: 'decimals' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'initialize',
    inputs: [
      { type: 'string', name: 'name' },
      { type: 'string', name: 'symbol' },
      { type: 'uint8', name: 'decimals' },
      { type: 'address[]', name: 'minters' },
      { type: 'address[]', name: 'pausers' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'initialize',
    inputs: [
      { type: 'string', name: 'name' },
      { type: 'string', name: 'symbol' },
      { type: 'uint8', name: 'decimals' },
      { type: 'uint256', name: 'initialSupply' },
      { type: 'address', name: 'initialHolder' },
      { type: 'address[]', name: 'minters' },
      { type: 'address[]', name: 'pausers' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'initialize',
    inputs: [{ type: 'address', name: 'sender' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '' }],
    name: 'isMinter',
    inputs: [{ type: 'address', name: 'account' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '' }],
    name: 'isPauser',
    inputs: [{ type: 'address', name: 'account' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '' }],
    name: 'isSurveyRegistered',
    inputs: [{ type: 'address', name: '_survey' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'string', name: '' }],
    name: 'name',
    inputs: [],
    constant: true,
  },
  { type: 'function', stateMutability: 'nonpayable', outputs: [], name: 'pause', inputs: [], constant: false },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '' }],
    name: 'paused',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'registerSurvey',
    inputs: [{ type: 'address', name: '_survey' }],
    constant: false,
  },
  { type: 'function', stateMutability: 'nonpayable', outputs: [], name: 'renounceMinter', inputs: [], constant: false },
  { type: 'function', stateMutability: 'nonpayable', outputs: [], name: 'renouncePauser', inputs: [], constant: false },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'string', name: '' }],
    name: 'symbol',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '' }],
    name: 'totalSupply',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '' }],
    name: 'transfer',
    inputs: [
      { type: 'address', name: 'recipient' },
      { type: 'uint256', name: 'amount' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '' }],
    name: 'transferFrom',
    inputs: [
      { type: 'address', name: 'sender' },
      { type: 'address', name: 'recipient' },
      { type: 'uint256', name: 'amount' },
    ],
    constant: false,
  },
  { type: 'function', stateMutability: 'nonpayable', outputs: [], name: 'unpause', inputs: [], constant: false },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'unregisterSurvey',
    inputs: [{ type: 'address', name: '_survey' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'pure',
    outputs: [{ type: 'uint256', name: '' }],
    name: 'version',
    inputs: [],
    constant: true,
  },
  {
    type: 'event',
    name: 'Approval',
    inputs: [
      { type: 'address', name: 'owner', indexed: true },
      { type: 'address', name: 'spender', indexed: true },
      { type: 'uint256', name: 'value', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MinterAdded',
    inputs: [{ type: 'address', name: 'account', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MinterRemoved',
    inputs: [{ type: 'address', name: 'account', indexed: true }],
    anonymous: false,
  },
  { type: 'event', name: 'Paused', inputs: [{ type: 'address', name: 'account', indexed: false }], anonymous: false },
  {
    type: 'event',
    name: 'PauserAdded',
    inputs: [{ type: 'address', name: 'account', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PauserRemoved',
    inputs: [{ type: 'address', name: 'account', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { type: 'address', name: 'from', indexed: true },
      { type: 'address', name: 'to', indexed: true },
      { type: 'uint256', name: 'value', indexed: false },
    ],
    anonymous: false,
  },
  { type: 'event', name: 'Unpaused', inputs: [{ type: 'address', name: 'account', indexed: false }], anonymous: false },
] as const
